reviewers:
  # The default reviewers
  defaults:
    - repository-owners # GitHub team

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    repository-owners:
      - Jacob953 # username
      - DevRickLin # username
    core-manager:
      - jzndd # username
    science:
      - DevRickLin # username
      - typedrandomly # username
    bigdata:
      - tangent-heng # username
      - Yemonade # username
    security:
      - Gstalker # username
      - the-fall-moon # username
      - wbfwonderful # username
    automation:
      - jzndd # username
    intelligence:
      - M-Chase # username
      - heyzbw # username

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**/science/**':
    - science # group
  '**/bigdata/**':
    - bigdata # group
  '**/security/**':
    - security # group
  '**/intelligence/**':
    - intelligence # group
  '**':
    - repository-owners # group
    - core-manager # group

options:
  ignore_draft: false
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false